<?php


namespace Nemundo\ToDo\Widget;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Admin\Com\Widget\AbstractAdminWidget;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\ToDo\Com\ToDoForm;
use Nemundo\ToDo\Com\ToDoTable;
use Nemundo\ToDo\Data\ToDo\ToDoReader;
use Nemundo\ToDo\Site\ToDoSite;
use Nemundo\User\Session\UserSession;
use Nemundo\User\Type\UserSessionType;

class ToDoWidget extends AbstractAdminWidget
{

    protected function loadWidget()
    {
       $this->widgetTitle='To Do';
       $this->widgetSite= ToDoSite::$site;
    }


    public function getContent()
    {

        $form =new ToDoForm($this);

        $table = new ToDoTable($this);
        $table->showDoneItem=false;

        /*
        $table = new AdminTable($this);

        $toDoReader = new ToDoReader();
        $toDoReader->filter->andEqual($toDoReader->model->userId, (new UserSession())->userId);
        $toDoReader->addOrder($toDoReader->model->toDo);
        foreach ($toDoReader->getData() as $toDoRow) {

            $row = new TableRow($table);
            $row->addText($toDoRow->toDo);

        }*/



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}