<?php


namespace Nemundo\ToDo\Workflow\Form;


use Nemundo\Package\Bootstrap\FormElement\BootstrapLargeTextBox;
use Nemundo\Process\Form\AbstractStatusForm;
use Nemundo\ToDo\Data\Comment\Comment;

class CommentForm extends AbstractStatusForm
{

    /**
     * @var BootstrapLargeTextBox
     */
    private $comment;

    public function getContent()
    {

        $this->comment = new BootstrapLargeTextBox($this);
        $this->comment->label='Comment';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {
        // TODO: Implement onSubmit() method.

        $data = new Comment();
        $data->comment = $this->comment->getValue();
        $this->dataId = $data->save();

        $this->saveWorkflowLog();


    }

}