<?php


namespace Nemundo\ToDo\Workflow\Process;


use Nemundo\Process\Workflow\Content\Item\Process\WorkflowItem;
use Nemundo\Process\Workflow\Content\Process\AbstractProcess;
use Nemundo\Process\Workflow\Content\Status\ProcessStatusTrait;
use Nemundo\ToDo\Content\ToDoContentList;
use Nemundo\ToDo\Data\ToDo\ToDo;
use Nemundo\ToDo\Workflow\Status\CreateProcessStatus;
use Nemundo\ToDo\Workflow\View\ToDoView;
use Nemundo\User\Session\UserSession;

class ToDoProcess extends AbstractProcess
{

    use ProcessStatusTrait;

    protected function loadContentType()
    {

        $this->type = 'To Do (Aufgabe)';
        //$this->type = 'ToDo';
        $this->contentId = '6925df2d-ee59-49d4-aa8b-c03e0900f589';
        $this->prefixNumber = 'TODO-';
        $this->startNumber = 200;
        $this->startContentType = new CreateProcessStatus();
        $this->viewClass = ToDoView::class;
        $this->listClass=ToDoContentList::class;
        $this->itemClass=WorkflowItem::class;


    }


    /**
     * @var string
     */
    public $toDo;


    protected function saveData()
    {

        //$this->contentType = new ToDoProcess();
        $this->subject = $this->toDo;

        //$this->assignment->setUserIdentification((new UserSession())->userId);
        //$this->assignment->setUsergroupIdentification(())

        //$this->saveWorkflow();

        $data = new ToDo();
        $data->id = $this->dataId;
        $data->updateOnDuplicate = true;
        $data->toDo = $this->toDo;
        //$data->workflowId = $this->dataId;
        $data->userId = (new UserSession())->userId;
        $data->save();


        /*
        $item = new AddGroupContentItem();
        $item->parentId = $this->dataId;
        $item->saveItem();*/


        /*
                $item = new UserAssignmentItem();
                $item->parentId= $this->dataId;
                $item->userId = (new UserSession())->userId;
                $item->saveItem();*/

    }


    /*
    public function getSubject()
    {



        return parent::getSubject($dataId); // TODO: Change the autogenerated stub
    }*/


}