<?php


namespace Nemundo\ToDo\Workflow\View;


use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Process\View\AbstractStatusView;
use Nemundo\ToDo\Data\Comment\CommentReader;

class CommentView extends AbstractStatusView
{

    public function getContent()
    {

        $commentRow = (new CommentReader())->getRowById($this->dataId);

        $p= new Paragraph($this);
        $p->content=$commentRow->comment;

        return parent::getContent(); // TODO: Change the autogenerated stub

    }

}