<?php


namespace Nemundo\ToDo\Workflow\View;


use Nemundo\Process\Com\Table\BaseWorkflowTable;
use Nemundo\Process\View\AbstractContentView;

class ToDoView extends AbstractContentView
{

    public function getContent()
    {

        $table = new BaseWorkflowTable($this);
        $table->workflowId=$this->dataId;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}