<?php


namespace Nemundo\ToDo\Workflow\View;


use Nemundo\Admin\Com\Title\AdminSubtitle;
use Nemundo\Process\Content\View\AbstractContentView;
use Nemundo\Process\Workflow\Com\Table\BaseWorkflowTable;
use Nemundo\ToDo\Workflow\Process\ToDoProcess;

class ToDoView extends AbstractContentView
{

    /**
     * @var ToDoProcess
     */
    public $contentType;

    public function getContent()
    {

        //$todoProcess = new ToDoProcess($this->dataId);

        $todoRow = $this->contentType->getDataRow();


        $title = new AdminSubtitle($this);
        $title->content = $todoRow->toDo;

        //$table = new BaseWorkflowTable($this);
        //$table->workflowId = $todoRow->workflowId;  //  $this->dataId;

        //$item = new ContentItem($this->dataId);
        /* $type =new ToDoProcess();
         $type->getViewSite($this->dataId);


         $btn = new AdminSiteButton($this);
         $btn->site =  $type->getViewSite($this->dataId);*/


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}