<?php


namespace Nemundo\ToDo\Content\App;


use Nemundo\Process\App\Application\Content\ApplicationContentType;
use Nemundo\Process\Content\Type\AbstractTreeContentType;


// contenttype setup
// extens Applicat

class ToDoApp extends ApplicationContentType  // AbstractTreeContentType
{


    protected function loadContentType()
    {
        parent::loadContentType(); // TODO: Change the autogenerated stub

        $this->application='To Do App';
        $this->applicationId = 'fbdcb91d-7f56-4b65-9bcb-04ffdb19349e';

    }





    /*
    protected function loadContentType()
    {

        $this->typeLabel = 'To Do';
        $this->typeId = '510c40d1-0adc-4bfb-bae1-8df3133c3918';
        $this->dataId = 'fbdcb91d-7f56-4b65-9bcb-04ffdb19349e';

    }*/

}